substitutions:
  name: gopes-occupancy
  friendly_name: "GOPES Occupancy"

# Initial minimal device configuration for setup
esphome:
  name: "${name}"
  name_add_mac_suffix: true
  friendly_name: "${friendly_name}"
  project:
    name: "guppi.gopes"
    version: "1.0.0"
    description: "GUPPI Occupancy and Human Presence Sensor"
  external_components:
    - source:
        type: git
        url: https://github.com/AdmiralArgyle/GOPES
      components: [gopes]
      refresh: 1d

# Basic ESP32 configuration
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable minimal logging
logger:
  level: WARN
  baud_rate: 0

# Enable API with encryption
api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s

# Enable OTA updates
ota:
  password: !secret ota_password

# Enable Improv for initial setup
improv_serial:
  friendly_name: "${friendly_name}"

# WiFi configuration with Improv
wifi:
  use_address: gopes-occupancy.local
  output_power: 20dB
  retry_timeout: 15min
  ap:
    ssid: "GOPES-Setup-${name}"
    password: !secret fallback_ap_password
  ap_timeout: 3min
  domain: .local
  power_save_mode: none
  reboot_timeout: 0s
  fast_connect: true

# Enable web server for Improv
web_server:
  port: 80
  include_internal: true

# UART Configuration for LD2410
uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 256000

# I2C Configuration for VL53L1X, BME280, and BH1750
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  frequency: 400kHz

# GOPES Component Configuration
gopes:
  # LD2410 Sensor Configuration
  moving_distance:
    name: "${friendly_name} Moving Distance"
  still_distance:
    name: "${friendly_name} Still Distance"
  detection_distance:
    name: "${friendly_name} Detection Distance"
  moving_energy:
    name: "${friendly_name} Moving Energy"
  still_energy:
    name: "${friendly_name} Still Energy"

  # Environmental Sensors
  temperature:
    name: "${friendly_name} Temperature"
  humidity:
    name: "${friendly_name} Humidity"
  pressure:
    name: "${friendly_name} Pressure"
  illuminance:
    name: "${friendly_name} Illuminance"

# MQTT Configuration
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: "${name}"
  discovery: true
  discovery_prefix: homeassistant
  topic_prefix: "GUPPI/GOPES/${name}"
  birth_message:
    topic: "GUPPI/GOPES/${name}/status"
    payload: "online"
  will_message:
    topic: "GUPPI/GOPES/${name}/status"
    payload: "offline"
  keepalive: 60s