substitutions:
  name: gopes-occupancy
  friendly_name: "GOPES Occupancy"

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: latest

logger:
  level: DEBUG
  baud_rate: 115200

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

# Enable Home Assistant API
api:
  encryption:
    key: "Fg6xZOM8Lgc2SjgvqBF6mi88ZnrhXG9HAlExLlLRhpk="

ota:

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot
  ap:
    ssid: "${friendly_name}"
    password: !secret fallback_ap_password
    
web_server:
  port: 80

captive_portal:

# I2C Configuration for BME680
# Using recommended GPIO pins for WROOM-32
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  frequency: 400kHz  # Added optimal frequency for BME680

# UART Configuration for LD2410
# Using recommended GPIO pins for WROOM-32
uart:
  id: uart_radar
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

# LD2410 Configuration
ld2410:
  uart_id: uart_radar
  timeout: 60s  # Added timeout configuration
  on_presence:  # Added presence detection events
  on_absence:

# User configurable offsets
number:
  - platform: template
    name: "Temperature Offset"
    id: temperature_offset
    optimistic: true
    min_value: -10
    max_value: 10
    step: 0.1
    restore_value: true
    initial_value: 0
    entity_category: "config"
    
  - platform: template
    name: "Humidity Offset"
    id: humidity_offset
    optimistic: true
    min_value: -20
    max_value: 20
    step: 0.1
    restore_value: true
    initial_value: 0
    entity_category: "config"

# BME680 configuration using BSEC2
bme68x_bsec2_i2c:
  id: bme68x_sensor
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V
  address: 0x77
  state_save_interval: 6h
  
binary_sensor:
  # Add occupancy sensor from LD2410
  - platform: ld2410
    has_target:
      name: "Presence Detection"
    has_moving_target:
      name: "Movement Detection"
    has_still_target:
      name: "Still Target Detection"

sensor:
  # Add LD2410 sensors
  - platform: ld2410
    moving_target_distance:
      name: "Moving Target Distance"
    still_target_distance:
      name: "Still Target Distance"
    moving_target_energy:
      name: "Moving Target Energy"
    still_target_energy:
      name: "Still Target Energy"
      
  # BME680 Sensors using BSEC2
  - platform: bme68x_bsec2
    bme68x_bsec2_id: bme68x_sensor
    temperature:
      name: "Temperature"
      id: raw_temperature
      internal: true
    pressure:
      name: "Pressure"
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 3
    humidity:
      name: "Humidity"
      id: raw_humidity
      internal: true
    gas_resistance:
      name: "Gas Resistance"
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 3
    iaq:
      name: "IAQ"
      id: iaq
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 3
    co2_equivalent:
      name: "CO2 Equivalent"
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 3
    breath_voc_equivalent:
      name: "Breath VOC Equivalent"
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 3

  # Compensated temperature sensor
  - platform: template
    name: "Temperature Compensated"
    id: compensated_temperature
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    lambda: |-
      return id(raw_temperature).state + id(temperature_offset).state;
    update_interval: 60s

  # Compensated humidity sensor
  - platform: template
    name: "Humidity Compensated"
    id: compensated_humidity
    unit_of_measurement: "%"
    device_class: "humidity"
    state_class: "measurement"
    accuracy_decimals: 1
    lambda: |-
      return id(raw_humidity).state + id(humidity_offset).state;
    update_interval: 60s

  - platform: uptime
    id: uptime_sensor
    internal: true
    update_interval: 60s

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

text_sensor:
  - platform: bme68x_bsec2
    bme68x_bsec2_id: bme68x_sensor
    iaq_accuracy:
      name: "IAQ Accuracy"

  - platform: template
    name: "IAQ Classification"
    lambda: |-
      if (int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Extremely polluted"};
      }
      else {
        return {"error"};
      }

  - platform: template
    name: "Formatted Uptime"
    lambda: |-
      uint32_t dur = id(uptime_sensor).state;
      int days = dur / 86400;
      int hours = (dur % 86400) / 3600;
      int minutes = (dur % 3600) / 60;
      int seconds = dur % 60;
      char buffer[50];
      if (days > 0) {
        sprintf(buffer, "%dd %02dh %02dm %02ds", days, hours, minutes, seconds);
      } else if (hours > 0) {
        sprintf(buffer, "%02dh %02dm %02ds", hours, minutes, seconds);
      } else if (minutes > 0) {
        sprintf(buffer, "%02dm %02ds", minutes, seconds);
      } else {
        sprintf(buffer, "%02ds", seconds);
      }
      return {buffer};
    update_interval: 60s

debug:
  update_interval: 30s

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
    id: reboot_esp